samvera-labs/avalon-bundle

Gemfile
Gemfile.lock
README.md
config/database.yml
db/schema.rb
docker-compose.yml

Part of https://github.com/avalonmediasystem/avalon/issues/2757

Add Docker and Postgres support

---

.eslintrc.js
.gitignore
config/webpack/environment.js
config/webpack/test.js
karma.conf.js
package.json
yarn.lock

I also updated the documentation for how/where to add spec files for our configuration:  https://github.com/avalonmediasystem/avalon-bundle/wiki/Front-End-Resources

Configure webpacker and karma jasmine unit testing setup

---

circle.yml

Update nodejs version

---

Capfile
Gemfile
Gemfile.lock
README.md
config/deploy.rb
config/deploy/docker.rb
db/schema.rb
docker-compose.yml

Fixes https://github.com/avalonmediasystem/avalon/issues/2773

Add Capistrano for automating deploys

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

In support of avalonmediasystem/avalon#2849.

Enable use of Hyrax's factories

---

Gemfile
Gemfile.lock
spec/features/create_generic_work_spec.rb
spec/rails_helper.rb

Install `database_cleaner` and setup it and `active_fedora/cleaner` the same way Hyrax does.

Configure cleaning the database and fedora for tests

---

.rubocop.yml
Gemfile

Fix gem ordering in Gemfile and exclude external files from rubocop

---

app/models/solr_document.rb
app/presenters/hyrax/audiovisual_work_presenter.rb
config/initializers/hyrax.rb
spec/presenters/hyrax/audiovisual_work_presenter_spec.rb

Fixes #82 
Adds metadata fields to manifest configuration.

Add configuration for iiif manifest metadata

---

app/presenters/hyrax/audiovisual_work_presenter.rb
config/environments/test.rb
config/locales/audiovisual_work.en.yml
spec/presenters/hyrax/audiovisual_work_presenter_spec.rb

Fixes #82 
Use correct labels for manifest metadata.

Fix metadata labels

---

Gemfile
Gemfile.lock

Upgrade to hyrax 2.1!

---

app/presenters/hyrax/audiovisual_work_presenter.rb
spec/presenters/hyrax/audiovisual_work_presenter_spec.rb

Override manifest_metadata instead of manifest

---

db/migrate/20180601183220_add_branding_to_collection_type.hyrax.rb
db/migrate/20180601183221_add_badge_color_to_collection_types.hyrax.rb

Add missing migrations for Hyrax 2.1

---

Gemfile.lock

Fix stale Gemfile.lock

---

Gemfile
Gemfile.lock

https://groups.google.com/forum/#!topic/ruby-security-ann/2S9Pwz2i16k

Update sprockets due to security vulnerability

---

docker-compose.yml

This should fix Bamboo deploy to Fluorine

Pin Fedora at 4.7.5

---

app/presenters/hyrax/av_file_set_presenter.rb
db/schema.rb

Fixes https://github.com/samvera-labs/avalon-bundle/pull/151/files#r196144150.

Avoid inline rescue

---

app/javascript/packs/react-iiif-media-player-pack.js
config/deploy.rb

Fixes #issuenumber ; refs #issuenumber
Present tense short summary (50 characters or less)
More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.
Description can have multiple paragraphs and you can use code examples inside:
``` ruby
class PostsController
def index
respond_with Post.limit(10)
end
end
```
Changes proposed in this pull request:
*
*
*

Issue#145: fix turbolink:load

---

app/javascript/react/containers/IIIFMediaPlayerContainer.js
package.json
yarn.lock

Configure credentials using newest version of react iiif player component

---

Gemfile
Gemfile.lock

The `v3_range_improvements` branch was merged and deleted so this PR points to master again.  We'll pick up @yingfeng-iu 's branch as well when that gets merged into master.

Move back to master branch for iiif_manifest

---

Gemfile.lock

Bump iiif_manifest to get language maps

---

config/deploy.rb

Keep only 5 cap releases now that we've fixed #174

---

Gemfile.lock

Bump versions of nokogiri and loofah to deal with security issues

---

.gitignore
Gemfile
Gemfile.lock
app/services/ffmpeg_option_service.rb
config/initializers/hyrax.rb
config/settings.yml
docker-compose.yml
package.json
spec/services/ffmpeg_option_service_spec.rb
yarn.lock

Enable streaming in Avalon with nginx

---

config/deploy/docker.rb

Capistrano retains tmp for streaming derivatives

---

Gemfile
docker-compose.yml

Batch wasn't working with sqlite

Use Postgres in development to fix sqlite lock issue

---

Gemfile
Gemfile.lock
app/models/file_set.rb
app/presenters/hyrax/av_file_set_presenter.rb
app/views/hyrax/base/_encode_progress.html.erb
app/views/hyrax/base/iiif_viewers/_avalon.html.erb
config/initializers/hyrax.rb
config/routes.rb
db/migrate/20190111234734_create_active_encode_encode_records.active_encode.rb
db/schema.rb
spec/presenters/hyrax/av_file_set_presenter_spec.rb

This PR does the final work of showing the status in the work view page.  More of this could probably be pushed into `hyrax-active_encode`.
Connected to https://github.com/samvera-labs/avalon-bundle/issues/254

Encode status

---

docker/Dockerfile

Upgrade fits to 1.4.1 and deal with mediainfo library issues

---

config/workflows/avalon_workflow.json

Adds a basic workflow for avalon that enables publish/unpublish.
Still missing: editor role(?), permalink minting

Add first draft of avalon workflow.

---

config/workflows/avalon_workflow.json

Add initial state

---

docker/rails_init-dev.sh

Admin set wasn't getting created on startup

Fix timing issue in bundle calls with admin set

---

.solr_wrapper
Gemfile
Gemfile.lock
app/controllers/application_controller.rb
config/application.rb
config/environments/development.rb
config/routes.rb

Implement IIIF Auth using hyrax-iiif_av

---

.circleci/config.yml
docker-compose.yml

Co-authored-by: Michael Johnson <mj82@iu.edu>

Use the latest avalon bundle tag from Docker
